site_name: smallzh's python
#site_url: https://github.com/smallzh/smallzh.python

nav:
    - 介绍: index.md
    - 数据类型: data_type.md
    - 字符串: string.md
    - 注释: notes.md
    - 流程控制: process_control.md
    - 函数: function.md
    - 内部函数: inner_function.md
    - 类: class.md
    - 模块: modules.md
    - 迭代器生成器: iterator_generator.md
    - 文件: file.md
    - 命令行: command_line.md
    - 一切皆对象: all_is_object.md
    - 运行模型: run_model.md
    - pip: pip.md
    - setup: setup.md
    - uv: uv.md
    - 海龟绘图: python_turtle.md
    - Flask: flask.md
    - SQLAlchemy: sqlalchemy.md
    - streamlit: streamlit.md
    - scapy: scapy.md
    - 数学库: math_lib.md

theme:
   name: gitbook

plugins: []
